//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.ResourcesFiles.DefaultLanguage", typeof(DefaultLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заборонено надсилати запит.
        /// </summary>
        public static string ActionForbidden {
            get {
                return ResourceManager.GetString("ActionForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний логін або пароль.
        /// </summary>
        public static string BadLoginOrPassword {
            get {
                return ResourceManager.GetString("BadLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі повинні співпадати.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступний запит для підтвердження електронної адреси буде доступний через {0}.
        /// </summary>
        public static string ConfigEmailActionMessage {
            get {
                return ResourceManager.GetString("ConfigEmailActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступний запит для відновлення паролю буде доступний через {0}.
        /// </summary>
        public static string ConfigPasswordActionMessage {
            get {
                return ResourceManager.GetString("ConfigPasswordActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступне відправлення відповіді буде доступне через {0}.
        /// </summary>
        public static string ConfigTaskAnswerAmountActionMessage {
            get {
                return ResourceManager.GetString("ConfigTaskAnswerAmountActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть імейл.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть підтвердження паролю.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завдання було успішно видалено.
        /// </summary>
        public static string DeleteAssignmentSuccess {
            get {
                return ResourceManager.GetString("DeleteAssignmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запит для підтвердження електронної адреси був надісланий на {0}.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронну адресу підтверджено успішно.
        /// </summary>
        public static string EmailConfirmSuccess {
            get {
                return ResourceManager.GetString("EmailConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист на підтвердження був надісланий знову.
        /// </summary>
        public static string EmailConfirmWasSendAgain {
            get {
                return ResourceManager.GetString("EmailConfirmWasSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено невірну адресу електронної пошти.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свою електронну пошту.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця електронна адреса не доступна.
        /// </summary>
        public static string EmailIsUsed {
            get {
                return ResourceManager.GetString("EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не знайдено.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступне введення паролю буде доступне через {0}.
        /// </summary>
        public static string LoginActionMessage {
            get {
                return ResourceManager.GetString("LoginActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це ім&apos;я користувача не доступне.
        /// </summary>
        public static string NicknameIsUsed {
            get {
                return ResourceManager.GetString("NicknameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запит на зміну пароля надісланий на {0}. Будь ласка відкрийте вашу електронну пошту.
        /// </summary>
        public static string PasswordChangeRequest {
            get {
                return ResourceManager.GetString("PasswordChangeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль було успішно змінено.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль повинен містити одну малу та велику літеру, одне число та бути в межах 8 та 16 символів.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото не знайдено.
        /// </summary>
        public static string PhotoNotFound {
            get {
                return ResourceManager.GetString("PhotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запит на перерахунок балів успішний.
        /// </summary>
        public static string RecalculateSuccess {
            get {
                return ResourceManager.GetString("RecalculateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь була успішно надіслана.
        /// </summary>
        public static string SetAnswer {
            get {
                return ResourceManager.GetString("SetAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так... Ми працюємо над проблемою.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото успішно отримано.
        /// </summary>
        public static string SuccessPhoto {
            get {
                return ResourceManager.GetString("SuccessPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен не дійсний.
        /// </summary>
        public static string TokenIsNotValid {
            get {
                return ResourceManager.GetString("TokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувача заблоковано. Зверніться до аміністратора.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення користувача не виконалося. Будь ласка перевірте деталі і спробуте знову.
        /// </summary>
        public static string UserCreationError {
            get {
                return ResourceManager.GetString("UserCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} успішно створено!.
        /// </summary>
        public static string UserCreationSuccess {
            get {
                return ResourceManager.GetString("UserCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис користувача повинен містити не більше 500 символів.
        /// </summary>
        public static string UserDescriptionLength {
            get {
                return ResourceManager.GetString("UserDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей користувач не існує!.
        /// </summary>
        public static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я користувача.
        /// </summary>
        public static string UsernameIsRequired {
            get {
                return ResourceManager.GetString("UsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача повинне містити від 2 до 64 символів.
        /// </summary>
        public static string UsernameLength {
            get {
                return ResourceManager.GetString("UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат фото.
        /// </summary>
        public static string UserPhotoInvalidFormat {
            get {
                return ResourceManager.GetString("UserPhotoInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмір фото профілю завеликий.
        /// </summary>
        public static string UserPhotoSizeTooLarge {
            get {
                return ResourceManager.GetString("UserPhotoSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінна {0} має бути введеною.
        /// </summary>
        public static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення {0} для поля {1} уже використовується.
        /// </summary>
        public static string ValueIsTaken {
            get {
                return ResourceManager.GetString("ValueIsTaken", resourceCulture);
            }
        }
    }
}
